### PR TITLE
Added BulkSMS Messaging adapter

### PR DESCRIPTION
**Pull request by Sukriti-m**
## What does this PR do?

This PR implements BulkSMS messaging adapter

## Test Plan

1. Create Your BulkSMS Account

2. Sign up for an account on [BulkSMS](https://www.bulksms.com/).

3. Set up Sender Information

4. Set up your phone number

5. Send the message.

Screenshot 2023-10-09 235907
Image shows the messages sent from a user's account

## Related PRs and Issues

Close [#6385](https://github.com/appwrite/appwrite/issues/6385)

### Have you read the [Contributing Guidelines on issues](https://github.com/utopia-php/messaging/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by wess** [comment]
Please, even if commented out, write a test, and be sure to run pint/linter. Thank you!

**Comment by gewenyu99** [comment]
Hey,

Due to time constraints, I'm going to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.

When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.

Thanks for helping us improve Appwrite!

**Comment by Sukriti-m** [comment]
> g to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.
> 
> When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.
> 
> Thanks for helping us improve Appwrite!

Thank You. I will be soon creating a PR with the required changes.

**Review by wess — CHANGES_REQUESTED** [review]
The linter is failing, i realize that the other test will fail for credentials, but please run the linter's formatter on it

**Review by wess — APPROVED** [review]

**Comment by gewenyu99** [comment]
https://github.com/utopia-php/messaging/pull/48

**Pull request closed without merging**
