### PR TITLE
Feat: Added Gupshup Messaging Adapter

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
## What does this PR do?
This PR implement support for Gupshup in the Utopia PHP messaging library.

Fixes: https://github.com/appwrite/appwrite/issues/6863

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/6863

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/utopia-php/messaging/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by HarshitVashisht11** [comment]
Hi @gewenyu99 Please review my PR

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Great PR! 🤯 Would you please attach screenshots of successful tests.

**Comment by HarshitVashisht11** [comment]
> Great PR! 🤯 Would you please attach screenshots of successful tests.

Thanks for reviewing my PR. At the moment, I don't possess a Gupshup API key, which is why I'm unable to conduct testing.

**Comment by stnguyen90** [comment]
> Thanks for reviewing my PR. At the moment, I don't possess a Gupshup API key, which is why I'm unable to conduct testing.

So you, nor we, have any way of confirming what you did works...

**Comment by HarshitVashisht11** [comment]
So, is there any way I can test if my code works

**Comment by gewenyu99** [comment]
@HarshitVashisht11 😅 usually those who implement the code would know how it's meant to be tested. Please include and run your tests

**Pull request closed without merging**
