### PR TITLE
Create Bandwidth.php

### PR DESCRIPTION
**Pull request by professorabhay**
Added bandwidth.php as per ->  Improve Appwrite Messaging with Bandwidth Adapter #6383

### CODE REVIEW

**Comment by professorabhay** [comment]
https://github.com/appwrite/appwrite/issues/6383

**Comment by gewenyu99** [comment]
Hey,

Due to time constraints, I'm going to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.

When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.

Thanks for helping us improve Appwrite!

**Comment by wess** [comment]
Please make sure to do 2 things:
---

1. Add tests
2. Run the linter's formatter.

**Review by wess — CHANGES_REQUESTED** [review]
Need to be sure to do 2 things:
---

1. Add tests.
2. Run the linter's formatter.

**Comment by gewenyu99** [comment]
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

**Pull request closed without merging**
