### PR TITLE
Issue-4358: Add Code Linter To utopia-php/messaging

### PR DESCRIPTION
**Pull request by Rutam21**
## What

This PR aims to resolve the issue https://github.com/appwrite/appwrite/issues/4358.

## How

- Code Linter has been added to utopia-php/messaging repository.
- All existing files are formatted as per the Linting rules.
- PR Template has been followed as mentioned in https://github.com/utopia-php/ab/pull/7.

Fixes https://github.com/appwrite/appwrite/issues/4358

### Have you read the [Contributing Guidelines on issues](https://github.com/utopia-php/messaging/blob/master/CONTRIBUTING.md)?

- [x] Yes, I have read the [Contributing Guidelines on issues](https://github.com/utopia-php/messaging/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Rutam21** [comment]
@Meldiron Please review and suggest changes, if any. Thanks.

cc: @stnguyen90 @christyjacob4

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Comment by DhairyaMajmudar** [comment]
Hi @christyjacob4 @stnguyen90 one of my PR has been approved but still not yet merged as of which I am not able to get the hacktoberfest swags please spare some time to merge it. 

https://github.com/utopia-php/messaging/pull/54

Thank You : )

**Pull request merged**
